### ISSUE TITLE
句読点

### ISSUE THREAD

**Issue by sudahiroshi** [KOUSUKE555/syuusei_kougai#1]
カンマ，ピリオドに統一してください．

**Comment by sudahiroshi** [comment]
まだ「、」が残っているので「，」に統一してください．

**Comment by KOUSUKE555** [comment]
確認したところ，「、」が見当たらなかったので、その箇所を教えてほしいです．

**Comment by sudahiroshi** [comment]
別ファイルを見てました．最新のファイルを見たら治っていました．
ただ，ファイル名を変えないでください．
