### ISSUE TITLE
フォントに対する問題点が唐突に出てくる

### ISSUE THREAD

**Issue by sudahiroshi** [KOUSUKE555/syuusei_kougai#2]
前ぶりも何もなしに出てくるのは違和感があります．

**Comment by KOUSUKE555** [comment]
背景に書いていることは前ぶりではないのでしょうか.

**Comment by sudahiroshi** [comment]
背景から問題点に繋がる部分では，配置に関することしか述べられていません．
そのためフォントについて唐突と表現しました．

参考までに，「フォント 印象 研究」でググると，それなりに出てきます．
それらを参照しつつ，「フォントによる印象についての研究は行われているが，広告中のフォントに関する研究は行われていないことも問題となっている」という文章にすれば良さそうな気がします．
